### ISSUE TITLE
Scaffold for JS/CSS development

### ISSUE THREAD

**Issue by Aljullu** [Aljullu/woocommerce-gutenberg-emails#17]
#1 introduced the scaffold for the plugin, but in order to create Gutenberg components, we also need several tools for JS and CSS development: Webpack, React, etc.

There is a work in progress in the branch [`js-tools`](https://github.com/Aljullu/woocommerce-gutenberg-emails/tree/js-tools).

**Comment by ryelle** [comment]
What do you think of trying to [leverage `wp-scripts`](https://github.com/WordPress/gutenberg/tree/master/packages/scripts#build) for this? This way we don't need to manage any of the webpack, eslint, or babel config/dependencies - it just uses gutenberg defaults. I tried using it in [this side project](https://github.com/ryelle/wc-custom-styles/) and it definitely makes setup easier.

It might not be a great match if we're looking to merge with WC core, but it could be a good quick start.

**Comment by Aljullu** [comment]
I created #23 with the use of `wp-scripts`, I still needed to overwrite some configs, but it was a time-saver, thanks for the advice @ryelle!
